version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "songbase"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"